Sprint 3
kurban-b/middle.messenger.praktikum.yandex pull request #3
Opened 2023-03-07 13:24 UTC by kurban-b

2023-03-07 14:56 UTC, evgenygil requested changes

2023-03-07 14:56 UTC, evgenygil commented on package.json
> +    "chai": "^4.3.7",
Вроде бы не увидел тестов в коде, chai/mocha точно где-то используются и нужны?

2023-03-07 14:56 UTC, evgenygil commented on src/controllers/AuthController.ts
> +    this.api = new AuthApi();
Не критикал, но возможно попробовать не создавать в каждом контроллере отдельный экземпляр api а передавать его внутрь

2023-03-07 14:56 UTC, evgenygil commented on src/controllers/AuthController.ts
> +  public async signup(data: SignupData) {
Как-то не единообразно названы типы, там выше с префиксом `I` и `xPost`, а тут просто `xData`, скорее понятнее выглядит этот, но желательно к какому-то однообразному шаблону привести

2023-03-07 14:56 UTC, evgenygil commented on src/controllers/ChatsController.ts
> +      const state = store.getState() as {chat: { chats: Chats[]}};
Кастование не лучшая практика, почему тут он ругается на несоответствие типа? Или там не описано что может быть в State?

2023-03-07 14:56 UTC, evgenygil commented on src/controllers/ChatsController.ts
> +  public async deleteChat(chatId: number) {
Кажется неиспользуемый метод

2023-03-07 14:56 UTC, evgenygil commented on src/controllers/MessagesController.ts
> +    const userId = store.getState().auth?.profile.id;
По идее если не смогли зарезолвить userId дальнейшая логика бессмысленна, то есть можно выйти из функции написал что не смогли получить id

2023-03-07 14:56 UTC, evgenygil commented on src/index.ts
> +    if (!isProtectedRoute) {
Не очень понятно почему введена эта переменная, она не изменяется, всегда true?

2023-03-07 14:56 UTC, evgenygil commented on src/pages/messages/components/Chat/Chat.ts
> +                    {{{Button size="small" label="Добавить участника" view="link" onClick=onClickAddUser}}}
Рекомендовал бы вынести сами шаблоны непосредственно в отдельные файлы

2023-03-07 14:56 UTC, evgenygil commented on src/pages/login/components/LoginForm/index.ts
>  export default LoginForm;
Не так чтобы криминал тоже, но предложу ознакомиться со [статьей](https://medium.com/@Brisstor/%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BC%D1%8B-%D0%BE%D1%82%D0%BA%D0%B0%D0%B7%D0%B0%D0%BB%D0%B8%D1%81%D1%8C-%D0%BE%D1%82-export-default-%D0%B2-javascript-%D0%B8-%D0%B2%D0%B0%D0%BC-%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D0%B5%D1%82-%D0%BF%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B8%D1%82%D1%8C-%D1%82%D0%B0%D0%BA%D0%B6%D0%B5-cce6ac30d67b#:~:text=%D0%AD%D0%BA%D1%81%D0%BF%D0%BE%D1%80%D1%82%20%D0%BF%D0%BE%2D%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E%20%D0%B4%D0%B5%D0%BB%D0%B0%D0%B5%D1%82%20%D0%BD%D0%B5%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D1%8B%D0%BC,%D0%BA%D0%B0%D0%B6%D0%B4%D0%BE%D0%BC%20%D0%BC%D0%B5%D1%81%D1%82%D0%B5%20(%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B0%D1%8F%20%D0%BE%D0%BF%D0%B5%D1%87%D0%B0%D1%82%D0%BA%D0%B8).&text=%D0%92%20%D0%BF%D1%80%D0%BE%D1%82%D0%B8%D0%B2%D0%BE%D0%BF%D0%BE%D0%BB%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D1%8D%D1%82%D0%BE%D0%BC%D1%83%2C%20%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5%20%D1%8D%D0%BA%D1%81%D0%BF%D0%BE%D1%80%D1%82%D1%8B%20%D0%B4%D0%B5%D0%BB%D0%B0%D1%8E%D1%82%20%D1%82%D0%B0%D0%BA%D0%BE%D0%B9%20%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3%20%D1%82%D1%80%D0%B8%D0%B2%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC.) почему стоит испольовать именованые экспорты вместо дефолтных

2023-03-07 14:56 UTC, evgenygil commented on src/ui/components/DialogForm/index.ts
> +export default DialogForm;
тут на самом деле можно воспользоваться таким реэкспортом - `export * from "./DialogForm"`

2023-03-07 14:56 UTC, evgenygil commented on src/utils/core/base-api.ts
> +  public create?(_: unknown): Promise<unknown> { throw new Error('Not implemented'); }
Не очень вообще понятно зачем создавать абстрактный класс в текущей реализации, и точнее вот эти методы, все классы, которые от него наследуются имеют другие, свои методы

2023-03-07 14:56 UTC, evgenygil commented on src/utils/core/http-transport.ts
> +  headers?: Record<string, any>
Думаю тут может быть `string` вместо `any`

2023-03-07 14:56 UTC, evgenygil commented on src/utils/core/router.ts
> +      return Router.__instance;
Лучше (будет выглядеть логичнее и понятнее) реализовать метод `getInstance()` который либо вернет инстанс либо создаст если его нет

2023-03-07 14:56 UTC, evgenygil commented on src/utils/core/index.ts
> +  Router.go(href);
Где-то видел использование этого метода не как статического а у инстанса класса роутер, это может немного путать, в итоге каким образом его правильно использовать?

2023-03-07 14:56 UTC, evgenygil commented on src/utils/core/ws-transport.ts
> +      this.pingInterval = 0;
Как-то не много смутила эта переменная, изначально показалось что тут просто интервал в секундах, а в нее оказывается и сам интервал попадает

2023-03-07 14:56 UTC, evgenygil commented on src/utils/core/ws-transport.ts
> +      const data = JSON.parse(message.data);
Стоит обернуть в `try..catch`, вдруг невалидный `JSON`

2023-03-07 14:56 UTC, evgenygil commented on src/utils/types/users.ts
> +export interface UserRequestData {
По идее удобнее было бы хранить типы рядом с сущностями

2023-03-07 14:56 UTC, evgenygil commented on src/utils/core/router.ts
> +class Route {
Это класс не Router, как в названии файла, стоит создать думаю отдельный файл и разделить их (Route/Router)

2023-03-07 20:19 UTC, kurban-b commented on package.json
> +    "chai": "^4.3.7",
тесты в 3-ем спринте не пишем, но либу добавил) для прохождения тестов в PR нужна была либа

2023-03-07 20:42 UTC, kurban-b commented on src/controllers/ChatsController.ts
> +  public async deleteChat(chatId: number) {
да, возможность удаления чата не реализовано в плане ui, но апи предоставляет такую возможность и наличие такого метода, даже если не используется, не мешает на мой взгляд

2023-03-07 20:49 UTC, kurban-b commented on src/utils/core/index.ts
> +  Router.go(href);
он так и используется) вроде у роутера нет инстанса в проекте

2023-03-07 20:54 UTC, kurban-b commented on src/utils/types/users.ts
> +export interface UserRequestData {
ну, глобальные типы, которые не привязаны строго к одной сущности, а могут использоваться в других местах для типизации решил вынести в отдельный файл, такая практика существует в реальных проектах

2023-03-08 05:39 UTC, evgenygil commented on src/utils/core/index.ts
> +  Router.go(href);
А, меня смутило, что где-то он написан с маленькой буквы, например в AuthController, выглядит как инстанс, если бы кстати был не дефолтный экспорт скорее всего название импортируемого класса/переменной всегда везде было бы одинаковое

2023-03-08 05:45 UTC, evgenygil commented on src/utils/types/users.ts
> +export interface UserRequestData {
Глобальные типы да, которые используются по всему проекту, например какой-нибудь абстрактный `Nullable<T>` тип или `Result<T, R>` на разных уровнях, когда у нас есть например типы привязанные к api это логично хранить их на уровне api, а не в сторонней папке, тут предполагается что эти типы вообще к утилитам относятся как бы. Если представим ситуацию, что надо что-то удалить, перенести (понятно идея поможет), но чем дальше разбросаны взаимосвязанные сущности друг от друга тем сложнее их искать потом. Это не критично само собой

2023-03-08 06:48 UTC, merged